version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      TZ: Europe/Madrid
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./data/bd.sql:/docker-entrypoint-initdb.d/bd.sql
    ports:
      - "3312:3306"